In [ ]:
import pandas as pd
import numpy as np


dates = pd.date_range(start="2024-01-01", periods=100)
assets = ["bitcoin", "gold", "nifty"]
data = []

for asset in assets:
    if asset == "bitcoin":
        prices = np.random.randint(30000, 40000, size=33)
    elif asset == "gold":
        prices = np.random.randint(50000, 60000, size=33)
    else:  # nifty
        prices = np.random.randint(18000, 20000, size=34)

    for date, price in zip(dates, prices):
        data.append([date, asset, price])

df = pd.DataFrame(data, columns=["Date", "Asset", "Price"])

df.to_csv("portfolio_prices.csv", index=False)
print("file created sucessfully")

nan_rows = np.random.choice(df.index, 3, replace=False)
df.loc[nan_rows, "Price"] = np.nan


# CHECK
print(df.isna().sum())

df.to_csv("portfolio_prices_with_nan.csv", index=False)

df["Price"] = df.groupby("Asset")["Price"].ffill()

df[df["Price"].isna()]

file created sucessfully
Date     0
Asset    0
Price    3
dtype: int64

Empty DataFrame
Columns: [Date, Asset, Price]
Index: []

In [10]:
df["Price"] = df.groupby("Asset")["Price"].ffill()

df[df["Price"].isna()]

Empty DataFrame
Columns: [Date, Asset, Price]
Index: []

In [11]:
df.to_csv("portfolio_prices_tester.csv", index=False)

In [5]:
import pandas as pd

df = pd.read_csv("portfolio_prices_tester.csv")

df['daily_return'] = df.groupby('Asset')['Price'].pct_change()
risk_summary = df.groupby("Asset")["daily_return"].agg(
    Average_Return="mean",
    Risk="std"
)

print("Risk Summary:\n")
print(risk_summary)

# save risk report
risk_summary.to_csv("risk_report.csv")

# highest risk & return
print("\nHighest Risk Asset:", risk_summary["Risk"].idxmax())
print("Highest Return Asset:", risk_summary["Average_Return"].idxmax())

Risk Summary:

         Average_Return      Risk
Asset
bitcoin        0.014060  0.125214
gold           0.001410  0.071639
nifty          0.003248  0.041872

Highest Risk Asset: bitcoin
Highest Return Asset: bitcoin